[project]
name = "demonalone-js_addon-comfyui"
description = "These nodes are implemented in JavaScript to ensure a highly responsive interface and enable visual preview without page reloading. They complement the main DemonAlone-nodes-ComfyUI package but can also operate independently."
version = "1.1.0"
license = {file = "LICENSE"} 
# classifiers = [
#     "Environment :: GPU :: NVIDIA CUDA",    # NVIDIA CUDA support
# ]


[project.urls]
Repository = "https://github.com/DemonAlone/DemonAlone-JS_Addon-ComfyUI"
#  Used by Comfy Registry https://registry.comfy.org
"Bug Tracker" = "https://github.com/DemonAlone/DemonAlone-JS_Addon-ComfyUI/issues"

[tool.comfy]
PublisherId = "demonalone"
DisplayName = "DemonAlone-JS_Addon-ComfyUI"
Icon = "https://avatars.githubusercontent.com/u/25270760"
includes = [] 
# "requires-comfyui" = ">=1.0.0"  # ComfyUI version compatibility
